[package]
name = "fossfi"
description = "FossFi (FOSS Finance) Network State Contracts"
version = "0.1.0"
license = "ISC"

[toolchain]
acton = "trunk"

[contracts.FossFi]
display-name = "FossFi Parent"
src = "contracts/src/fossFi/FossFi.tolk"
depends = [
    "Lottery",                                                                                        # small number deployed easy upgrades
    { name = "FossFiWallet", kind = "library_ref", function = "fossFiWalletCompiledCodeLibraryRef" },
]

[contracts.FossFiWallet]
display-name = "FossFiWallet Child"
src = "contracts/src/fossFi/FossFiWallet.tolk"
depends = [
    { name = "DaoVoter", kind = "library_ref", function = "daoVoterCompiledCodeLibraryRef" },
    { name = "Following", kind = "library_ref", function = "followingCompiledCodeLibraryRef" },
    { name = "PersonalMinter", kind = "library_ref", function = "personalMinterCompiledCodeLibraryRef" },

]

[contracts.Following]
display-name = "Following Child"
src = "contracts/src/followers/followers.tolk"
depends = []


[contracts.Location]
display-name = "Location Aggregator"
src = "contracts/src/location/Location.tolk"
depends = [
    { name = "CityMap", kind = "library_ref", function = "cityMapCompiledCodeLibraryRef" },
]

[contracts.CityMap]
display-name = "City Map Index"
src = "contracts/src/location/CityMap.tolk"
depends = []

[contracts.Lottery]
display-name = "Lottery"
src = "contracts/src/lottery/lottery.tolk"
depends = []

[contracts.PersonalMinter]
display-name = "Personal Token Minter"
src = "contracts/src/personalMinter/personal.tolk"
depends = [
    { name = "PersonalWallet", kind = "library_ref", function = "personalWalletCompiledCodeLibraryRef" },
]

[contracts.PersonalWallet]
display-name = "Personal Token Wallet"
src = "contracts/src/personalMinter/personalWallet.tolk"
depends = []

[contracts.Dao]
display-name = "DAO Governance"
src = "contracts/src/dao/Dao.tolk"
depends = [
    { name = "DaoVoter", kind = "library_ref", function = "daoVoterCompiledCodeLibraryRef" },
]

[contracts.DaoVoter]
display-name = "DAO Voter Child"
src = "contracts/src/dao/DaoVoter.tolk"
depends = []

[test]
# ui = true
# ui-port = 12345
# fork-net = "testnet"
# fork-block-number = 72776090

[wrappers.tolk]
# output-dir = "tests/generated-wrappers"
# generate-test = true
# test-output-dir = "tests/generated-tests"

[wrappers.typescript]
# output-dir = "./wrappers-ts"

[fmt]
width = 100
# ignore = ["contracts/generated/*.tolk"]
separate-import-groups = true

[lint]
exclude = ["contracts/wrappers/*.*.tolk", "gen/*.tolk"]
max-warnings = 0                                        # fail on any warning

[lint.rules]
unused-variable = "deny"
mutable-variable-can-be-immutable = "warn"

[scripts]
loop = "acton build && acton wrapper --all && acton check --fix && acton fmt && acton build && acton wrapper --all"
deploy-emulation = "acton script contracts/scripts/deploy.tolk"
deploy-testnet = "acton script contracts/scripts/deploy.tolk --net testnet"
deploy-libs = "acton library publish FossFiWallet --amount 1 --wallet teleg -y && acton library publish DaoVoter --amount 1 --wallet teleg -y && acton library publish CityMap --amount 1 --wallet teleg -y"
deploy-personal = "acton script contracts/scripts/deploy-personal.tolk"
verify-personal = "acton script contracts/scripts/verify-personal.tolk"
jetton-change-admin = "acton script contracts/scripts/change-admin.tolk"
jetton-change-metadata = "acton script contracts/scripts/change-metadata.tolk"
jetton-claim-admin = "acton script contracts/scripts/claim-admin.tolk"
jetton-info = "acton script contracts/scripts/info.tolk"
jetton-mint = "acton script contracts/scripts/mint.tolk"
jetton-transfer = "acton script contracts/scripts/transfer.tolk"

[import-mappings]
acton = ".acton"
contracts = "contracts/src"
gen = "gen"
tests = "contracts/tests"
wrappers = "contracts/wrappers"

# Check full Acton.toml reference and all available keys:
# https://ton-blockchain.github.io/acton/docs/acton-toml
